# MongoDB Users Exporter
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-users-exporter
  namespace: microservices
  labels:
    app: mongodb-exporter
    instance: users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-exporter
      instance: users
  template:
    metadata:
      labels:
        app: mongodb-exporter
        instance: users
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9216'
    spec:
      serviceAccountName: mongodb-exporter-sa
      containers:
      - name: mongodb-exporter
        image: percona/mongodb_exporter:0.39.0
        args:
          - "--mongodb.uri=$(MONGODB_URI)"
        env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-users-exporter-secret
              key: uri
        ports:
        - containerPort: 9216
          name: metrics
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          runAsNonRoot: true
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-users-exporter
  namespace: microservices
  labels:
    app: mongodb-exporter
    instance: users
spec:
  ports:
  - port: 9216
    targetPort: metrics
    name: metrics
  selector:
    app: mongodb-exporter
    instance: users
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-users-exporter-secret
  namespace: microservices
type: Opaque
stringData:
  uri: "mongodb://admin:MongoDBUserPass123!@mongo-users.microservices.svc.cluster.local:27017/users_db?authSource=admin"
---
# MongoDB Inventory Exporter - similar but with inventory credentials
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongodb-exporter-sa
  namespace: microservices
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mongodb-exporter-scc-role
  namespace: microservices
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  resourceNames:
  - restricted
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mongodb-exporter-scc-binding
  namespace: microservices
subjects:
- kind: ServiceAccount
  name: mongodb-exporter-sa
  namespace: microservices
roleRef:
  kind: Role
  name: mongodb-exporter-scc-role
  apiGroup: rbac.authorization.k8s.io
