apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-exporter
  namespace: microservices
  labels:
    app: zookeeper-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper-exporter
  template:
    metadata:
      labels:
        app: zookeeper-exporter
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9141'
    spec:
      serviceAccountName: zookeeper-exporter-sa
      containers:
      - name: zookeeper-exporter
        image: dabealu/zookeeper-exporter:latest
        env:
        - name: ZK_SERVER
          value: "zookeeper.microservices.svc.cluster.local:2181"
        ports:
        - containerPort: 9141
          name: metrics
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          runAsNonRoot: true
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-exporter
  namespace: microservices
  labels:
    app: zookeeper-exporter
spec:
  ports:
  - port: 9141
    targetPort: metrics
    name: metrics
  selector:
    app: zookeeper-exporter
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: zookeeper-exporter-sa
  namespace: microservices
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: zookeeper-exporter-scc-role
  namespace: microservices
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  resourceNames:
  - restricted
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: zookeeper-exporter-scc-binding
  namespace: microservices
subjects:
- kind: ServiceAccount
  name: zookeeper-exporter-sa
  namespace: microservices
roleRef:
  kind: Role
  name: zookeeper-exporter-scc-role
  apiGroup: rbac.authorization.k8s.io
