apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql-gateway
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graphql-gateway
  template:
    metadata:
      labels:
        app: graphql-gateway
    spec:
      # Regular microservice uses restricted SCC (most secure)
      serviceAccountName: graphql-sa
      containers:
        - name: graphql-gateway
          image: clementbonal/microservice-project_graphql:v4
          ports:
            - containerPort: 4000
          env:
            - name: USERS_SERVICE_URL
              value: http://users-service:3001
            - name: ORDERS_SERVICE_URL
              value: http://orders-service:3002
            - name: INVENTORY_SERVICE_URL
              value: http://inventory-service:3003
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            runAsNonRoot: true
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: graphql-gateway
  namespace: microservices
spec:
  # ClusterIP - no LoadBalancer needed
  ports:
    - port: 4000
  selector:
    app: graphql-gateway
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: graphql-gateway
  namespace: microservices
  labels:
    app: graphql-gateway
spec:
  to:
    kind: Service
    name: graphql-gateway
  port:
    targetPort: 4000
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: graphql-sa
  namespace: microservices
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: graphql-scc-role
  namespace: microservices
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  resourceNames:
  - restricted
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: graphql-scc-binding
  namespace: microservices
subjects:
- kind: ServiceAccount
  name: graphql-sa
  namespace: microservices
roleRef:
  kind: Role
  name: graphql-scc-role
  apiGroup: rbac.authorization.k8s.io
