apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      serviceAccountName: inventory-service-sa
      initContainers:
        - name: wait-for-mongo
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z mongo-inventory.microservices.svc.cluster.local 27017; do echo waiting for mongo-inventory; sleep 10; done']
      containers:
        - name: inventory-service
          image: clementbonal/microservice-project_inventory-service:v2
          ports:
            - containerPort: 3003
          env:
            - name: MONGO_URI
              value: "mongodb://admin:MongoDBInventoryPass123!@mongo-inventory:27017/inventory_db?authSource=admin"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            runAsNonRoot: true
            # OpenShift will assign a random UID in the restricted range
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: microservices
spec:
  ports:
    - port: 3003
  selector:
    app: inventory-service
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: inventory-service-sa
  namespace: microservices
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: inventory-service-scc-role
  namespace: microservices
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  resourceNames:
  - restricted
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: inventory-service-scc-binding
  namespace: microservices
subjects:
- kind: ServiceAccount
  name: inventory-service-sa
  namespace: microservices
roleRef:
  kind: Role
  name: inventory-service-scc-role
  apiGroup: rbac.authorization.k8s.io
