apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-users
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-users
  template:
    metadata:
      labels:
        app: mongo-users
    spec:
      serviceAccountName: mongodb-sa
      containers:
        - name: mongo-users
          image: mongo:4.4
          args:
            - "--auth"  # Enable authentication
          env:
            - name: MONGO_INITDB_DATABASE
              value: users_db
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-users-secrets
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-users-secrets
                  key: password
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-users-storage
              mountPath: /data/db
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            runAsNonRoot: true
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      initContainers:
        - name: fix-permissions
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              chown -R 999:999 /data/db  # MongoDB user is UID 999
          volumeMounts:
            - name: mongo-users-storage
              mountPath: /data/db
          securityContext:
            runAsUser: 0
      volumes:
        - name: mongo-users-storage
          persistentVolumeClaim:
            claimName: mongo-users-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-users
  namespace: microservices
spec:
  ports:
    - port: 27017
  selector:
    app: mongo-users
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongodb-sa
  namespace: microservices
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mongodb-scc-role
  namespace: microservices
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  resourceNames:
  - anyuid
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mongodb-scc-binding
  namespace: microservices
subjects:
- kind: ServiceAccount
  name: mongodb-sa
  namespace: microservices
roleRef:
  kind: Role
  name: mongodb-scc-role
  apiGroup: rbac.authorization.k8s.io
