apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      serviceAccountName: zookeeper-sa
      containers:
        - name: zookeeper
          image: zookeeper:3.7.0
          ports:
            - containerPort: 2181
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
            - name: ZOOKEEPER_SASL_ENABLED
              value: "true"
            - name: ZOOKEEPER_ALLOW_ANONYMOUS_LOGIN
              value: "false"
            - name: ZOOKEEPER_JAAS_LOGIN_RENEW
              value: "3600000"
            - name: JVMFLAGS
              value: "-Djava.security.auth.login.config=/etc/kafka/zookeeper_jaas.conf"
            - name: ZOO_CFG_EXTRA
              value: "authProvider.1=org.apache.zookeeper.server.auth.SASLAuthenticationProvider sessionRequireClientSASLAuth=true"
          volumeMounts:
            - name: zookeeper-storage
              mountPath: /zookeeper
            - name: zookeeper-jaas
              mountPath: /etc/kafka
              readOnly: true
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            runAsNonRoot: true
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      initContainers:
        - name: fix-permissions
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              chown -R 1000:1000 /zookeeper
          volumeMounts:
            - name: zookeeper-storage
              mountPath: /zookeeper
          securityContext:
            runAsUser: 0
      volumes:
        - name: zookeeper-storage
          persistentVolumeClaim:
            claimName: zookeeper-pvc
        - name: zookeeper-jaas
          configMap:
            name: zookeeper-config
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: microservices
spec:
  ports:
    - port: 2181
      targetPort: 2181
      name: client
  selector:
    app: zookeeper
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: zookeeper-sa
  namespace: microservices
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: zookeeper-scc-role
  namespace: microservices
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  resourceNames:
  - anyuid
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: zookeeper-scc-binding
  namespace: microservices
subjects:
- kind: ServiceAccount
  name: zookeeper-sa
  namespace: microservices
roleRef:
  kind: Role
  name: zookeeper-scc-role
  apiGroup: rbac.authorization.k8s.io
